name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'packages/auth/**'
permissions: read-all

defaults:
  run:
    working-directory: packages/auth

jobs: 
  build:
    runs-on: ubuntu-latest
    environment: 
      name: development

    steps: 
      - uses: actions/checkout@v2
      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"

      # install dependencies
      - run: yarn install

      # build the react app
      - run: yarn build
      

      - name: ACTION_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV


      - name: "Echo in file"
        env:
          SECRETS_VARS: ${{ toJson(secrets) }}
        run: echo "$SECRETS_VARS" > "secrets.txt" 

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/auth/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/auth/latest/auth-entry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        
